WPF app
sergey-berezin/441_mikhalchuk pull request #2
Opened 2022-12-10 11:16 UTC by miilv

Added wpf app for task 2

2022-12-12 09:52 UTC, sergey-berezin requested changes
Надо удалить папки .vs из PR. Рекомендую настроить .gitignore

2022-12-12 09:52 UTC, sergey-berezin commented on WpfApp/WpfApp/MainWindow.xaml.cs
> +                            Tuple<float, float> pair = await Calculate(ImagePathsList.Item1[i], ImagePathsList.Item2[j], mlnet, cts);
Пока этот обработчик ожидает завершение задачи, он может быть вызвать ещё раз. От этого нужно защититься.

2022-12-19 08:37 UTC, sergey-berezin requested changes
В папке WpfApp есть папка .vs

2022-12-19 08:37 UTC, sergey-berezin commented on WpfApp/WpfApp/MainWindow.xaml.cs
> +                cts = new CancellationTokenSource();
Зачем в обработчике исключения создаётся новый экземпляр `CancellationTokenSource`?

2022-12-19 09:53 UTC, miilv commented
Resolved

2022-12-19 10:28 UTC, merged